version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
    volumes:
      - sqlite_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s

volumes:
  sqlite_data: