apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsu-demo
  namespace: devsu-demo-ns
  labels:
    app: devsu-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsu-demo
  template:
    metadata:
      labels:
        app: devsu-demo
    spec:
      initContainers:
      - name: init-db
        image: fernandre/devsu-demo:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Waiting for database connection..."
          python manage.py migrate
        envFrom:
        - configMapRef:
            name: devsu-demo-config
        - secretRef:
            name: devsu-demo-secrets
      containers:
      - name: devsu-demo
        image: fernandre/devsu-demo:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: devsu-demo-config
        - secretRef:
            name: devsu-demo-secrets
        livenessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30 